name: Deploy to gh-pages

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run generate

      - name: Deploy to gh-pages
        run: |
          git checkout gh-pages
          cp -R dist/* .
          git add .
          git commit -m "Update deployment"
          git push origin gh-pages
